export const STARTER_WORLD_USERS = [
  "torvalds",
  "antirez",
  "gvanrossum",
  "matz",
  "dhh",
  "nikic",
  "gaearon",
  "yyx990803",
  "sindresorhus",
  "mrdoob",
  "paulirish",
  "ryanflorence",
  "Rich-Harris",
  "developit",
  "tannerlinsley",
  "bradfitz",
  "tiangolo",
  "dtolnay",
] as const;
